### ISSUE TITLE
QUASINANO parameters ?

### ISSUE THREAD

**Issue by AndresOrtegaGuerrero** [gajh494c/SOC-DFTB#1]
Hello, 

I was wondering if the QUASINANO SK parameters are available ?

Since I didnt find them in the github

best, 

Andres

**Comment by gajh494c** [comment]
Hello,


I am really sorry. I was on vacation and I could not access my email. QUASINANO parameters are not available on GitHub. Those parameters are only available with AMS software or within our group as our lab developed the parameters.


Kind regards,

Gautam

________________________________
Von: AndresOrtegaGuerrero ***@***.***>
Gesendet: Dienstag, 26. Juli 2022 14:58:01
An: gajh494c/SOC-DFTB
Cc: Subscribed
Betreff: [gajh494c/SOC-DFTB] QUASINANO parameters ? (Issue #1)


Hello,

I was wondering if the QUASINANO SK parameters are available ?

Since I didnt find them in the github

best,

Andres
